backend/external/internal/clientHandler.go, backend/external/internal/http.go, backend/external/internal/syncController.go
=> receive from client and add to kvs

backend/external/internal/command2Internal.go, backend/external/internal/command2Internal_test.go, backend/external/internal/syncController_test.go
=> handle gRPC err

backend/positioning/Pipfile, backend/positioning/Pipfile.lock, backend/positioning/hallsensor.yaml, backend/positioning/visualize.py
ホールセンサー設定ファイルをためしに作った。pythonでいいかんじに可視化できんか？
=> add meidaimae to motoyawata

backend/external/pkg/clientHandler/embed/index.html, backend/external/pkg/servo/send.go
prometheusくんメトリクスをまとめてくれるらしいのでまとめます
=> delete unused prometheus exporter

frontend/Dockerfile, frontend/package.json
=> use nginx instead of next server by static HTML export

backend/internal/internalMock/mock.go
https://github.com/ueckoken/plarail2021-soft/runs/4190335484?check_suite_focus=true
=> fix code for success test 

backend/Makefile, backend/docker-compose.yaml, backend/internal/cmd/main.go, backend/internal/pkg/station2espIp/embed/station2espIp.yml
go tool pprof 'http://localhost:6060/debug/pprof/goroutine?seconds=60'
=> serve pprof

backend/internal/pkg/Send2Json/sendJson.go, backend/internal/pkg/msg2Esp/send.go, backend/internal/pkg/serveGrpc/ServeCommand2Internal.go, backend/internal/pkg/serveGrpc/ServeCommand2Internal_test.go, backend/internal/pkg/serveGrpc/serveGrpc.go
=> reuse http.client

frontend/components/RailRoadMap.tsx, frontend/components/svgParts/Rail.tsx, frontend/components/svgParts/Station.tsx, frontend/components/svgParts/StopPoint.tsx, frontend/components/svgParts/SwitchPoint.tsx, frontend/pages/index.tsx, frontend/types/svgPartsTypes.tsx, frontend/utils/util.ts
=> add railroad map SVG components and sample

frontend/.eslintrc.json, frontend/.prettierignore, frontend/components/RailRoadMap.tsx, frontend/components/svgParts/Rail.tsx, frontend/components/svgParts/Station.tsx, frontend/components/svgParts/StopPoint.tsx, frontend/components/svgParts/SwitchPoint.tsx, frontend/next.config.js, frontend/package.json, frontend/pages/_app.tsx, frontend/pages/api/hello.ts, frontend/pages/index.tsx, frontend/types/svgPartsTypes.tsx, frontend/utils/util.ts, frontend/yarn.lock
prettier is the de facto standard for code formatting
=> format via prettier

backend/external/pkg/syncController/embed/stationInit.yml
stationInit.yamlに全サーボ分追加しました。
stateを決める基準がわからなかったためすべて1にしています。
=> state全1で全サーボ追加

frontend/components/RailRoadMap.tsx, frontend/components/svgParts/Station.tsx, frontend/pages/index.tsx
=> remove stop rail from Station component

backend/docker-compose.yaml, backend/external/cmd/main.go, backend/external/internal/http.go, backend/external/pkg/clientHandler/embed/index.html, backend/external/pkg/syncController/syncController.go, backend/positioning/internal/http.go
あずきバーへ、websocketのやつまともに動かんことが判明したので治した。使う場合は気をつけて。
=> refactor and bugfix in handling websocket

frontend/components/RailRoadMap.tsx, frontend/pages/index.tsx, frontend/types/websocket-messages.ts
connect to WebSocket endpoint and sync all stop rails for debug
=> debug stop rails

frontend/components/RailRoadMap.tsx, frontend/pages/index.tsx
sync all bunki rails for debug
=> debug bunki rails

docs/svgcomponents.md
=> add SVG components document

.github/workflows/deploy-speed.yml
=> fix deploy workflow

frontend/components/svgParts/SpeedMeter.tsx, frontend/pages/index.tsx
=> add SpeedMeter

frontend/components/VideoCast.tsx, frontend/package.json, frontend/pages/index.tsx, frontend/videoCast/skyway_receiver.js, frontend/yarn.lock
まだroom_id aaaしか配信できないのとバグありそうなのでとりあえずなデプロイ
=> add video area

backend/external/pkg/servo/send.go, backend/external/pkg/servo/send_test.go, backend/external/pkg/syncController/syncController.go
挙動をパニックを起こすように修正した
エラーログを分かりやすくした
=> fix initializer

frontend/components/svgParts/StopPoint.tsx
Closes #240 
従来より縦長になったので地図上ではいくつか位置をずらす必要があるかもしれません
=> two-light signal

frontend/components/RailRoadMap.tsx, frontend/pages/index.tsx
=> sync stop rails

frontend/components/RailRoadMap.tsx, frontend/pages/index.tsx
`isLeft` が合ってるのかわかっていないですが後で直すことにします
=> sync switch points

backend/internal/pkg/esp32healthcheck/esp32Healthcheck.go
=> fix goroutine leak

frontend/components/VideoCast.tsx, frontend/pages/index.tsx, frontend/videoCast/momo_sender.html, frontend/videoCast/momo_sender.js
webカメラのwidth, height, framerateを設定可能にしました
=> Webrtc sender video config

frontend/components/RailRoadMap.tsx
=> refactor handwriting switch point

frontend/components/RailRoadMap.tsx, frontend/components/svgParts/StopPoint.tsx, frontend/components/svgParts/SwitchPoint.tsx, frontend/pages/index.tsx, frontend/tsconfig.json
=> select stop point or switch point to toggle

frontend/components/RailRoadMap.tsx
close #381 
操作を地図に統合する(#403 )とのことなので地図自体を拡大することで携帯からの操作性を確保できるだろう。
=> add cloce up map

frontend/components/RailRoadMap.tsx
ガバガバマージを修正
> conflict解消ﾖｼ
posted by @otariidae in https://github.com/ueckoken/plarail2021-soft/pull/411#pullrequestreview-811877473
ﾖｼではない
=> fix #411 merge miss

frontend/components/RailRoadMap.tsx
=> fix switch rail

frontend/pages/index.tsx
=> fix video style

manifests/infra/helm/kustomization.yaml, manifests/manifests/kustomization.yaml
Destroy all backend servers.
After merging this, I scale down server clusters to 1 node.
=> thanks for all servers!
